language: csharp
solution: DonetTravisCI.sln
install:
  - nuget restore DonetTravisCI.sln
  - nuget install  NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Debug DonetTravisCI.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./CSharpTravisCITests/bin/Debug/CSharpTravisCITests.dll 
